# .render.yaml

services:
  - type: web
    name: youtube-transcription-api
    env: python
    branch: develop
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app"
    region: oregon  # Ou sélectionne la région préférée